name: Repro build for https://github.com/etalab/transport-ops/issues/63
on:
  push:
    branches:
      - elixir-1.18
env:
  TEST_TAG: ${{ github.repository }}:test-debug
jobs:
  build-and-push-image:
    runs-on: [ubuntu-latest, macos-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # See https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@16c0bc4a6e6ada2cfd8afd41d22d95379cf7c32a # v2.8.0

      - name: Build and export to Docker
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: debug
          # "load: true" apparently exports the image on the client (no external push),
          # which is useful for testing it before any push.
          # see https://github.com/docker/build-push-action
          # --output=type=docker to enforce local work
          # https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#load
          # https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#docker
          load: true
          push: false # the default, but added for clarity
          tags: ${{ env.TEST_TAG }}

